config/routes.rb
Rails.application.routes.draw do
  resources :imap_providers
  devise_for :user, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  resources :user
  root 'home#index'
  get 'users/new'
  get 'users/index'
  get 'users/edit'
  get 'users/show'
  get "home", to: 'users#new'
  get "home", to: 'imap_providers#new'
  post "start_backup", to: 'backup#start_backup'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imap_provider.rb
class ImapProvider < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2]

  # def self.from_omniauth(auth)
  #   # Either create a User record or update it based on the provider (Google) and the UID   
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     user.token = auth.credentials.token
  #     user.expires = auth.credentials.expires
  #     user.expires_at = auth.credentials.expires_at
  #     user.refresh_token = auth.credentials.refresh_token
  #   end
  # end


  def self.from_omniauth(auth)
    user = User.find_by(email: auth.info.email)
    if user
      user.provider = auth.provider
      user.uid = auth.uid
      return user
    end
  
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.skip_confirmation! 
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
    before_action :authenticate_user!
end

app/controllers/backup_controller.rb
class BackupController < ApplicationController
    def start_backup
        options = {command: "backup"}

        begin
            configuration = Imap::Backup::Configuration::List.new(options[:accounts])
        rescue Imap::Backup::ConfigurationNotFound
            Imap::Backup::Configuration::Setup.new.run
            exit
        end
        
        configuration.setup_logging
        
        configuration.each_connection do |connection|
            connection.run_backup
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
      @users = User.all
      @imap_providers = ImapProvider.all
      @imap_backup_version = Imap::Backup::VERSION

  end

  def new_user
    @new_user = User.new
  end
  
  def create
    @new_user = User.create(new_user_params)
    redirects_to home_path
  end

  def start_backup
    options = {command: "backup"}

    begin
        configuration = Imap::Backup::Configuration::List.new(options[:accounts])
    rescue Imap::Backup::ConfigurationNotFound
        Imap::Backup::Configuration::Setup.new.run
        exit
    end
    
    configuration.setup_logging
    
    configuration.each_connection do |connection|
        connection.run_backup
    end
  end

  private
  def new_user_params
    params.require(:new_user).permit(:first_name, :last_name, :email)
  end
end

app/controllers/imap_providers_controller.rb
class ImapProvidersController < ApplicationController
  before_action :set_imap_provider, only: [:show, :edit, :update, :destroy]

  # GET /imap_providers
  # GET /imap_providers.json
  def index
    @imap_providers = ImapProvider.all
  end

  # GET /imap_providers/1
  # GET /imap_providers/1.json
  def show
  end

  # GET /imap_providers/new
  def new
    @imap_provider = ImapProvider.new
  end

  # GET /imap_providers/1/edit
  def edit
  end

  # POST /imap_providers
  # POST /imap_providers.json
  def create
    @imap_provider = ImapProvider.new(imap_provider_params)

    respond_to do |format|
      if @imap_provider.save
        format.html { redirect_to @imap_provider, notice: 'Imap provider was successfully created.' }
        format.json { render :show, status: :created, location: @imap_provider }
      else
        format.html { render :new }
        format.json { render json: @imap_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imap_providers/1
  # PATCH/PUT /imap_providers/1.json
  def update
    respond_to do |format|
      if @imap_provider.update(imap_provider_params)
        format.html { redirect_to @imap_provider, notice: 'Imap provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @imap_provider }
      else
        format.html { render :edit }
        format.json { render json: @imap_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imap_providers/1
  # DELETE /imap_providers/1.json
  def destroy
    @imap_provider.destroy
    respond_to do |format|
      format.html { redirect_to imap_providers_url, notice: 'Imap provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_imap_provider
      @imap_provider = ImapProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def imap_provider_params
      params.require(:imap_provider).permit(:name, :server, :port, :ssl)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :authenticate_user!

  def google_oauth2
    auth = request.env["omniauth.auth"]
    user = User.where(email: auth["info"]["email"], can_login: true).first # Got rid of this section, it creates the user if they dont exist#_or_initialize(email: auth["info"]["email"], password: Devise.friendly_token[0,20])
    #user.save!
    if !user
      raise "Sorry, your account is not registered, please contact your administrator"
    end
    user.remember_me = false
    sign_in(:user, user)
    redirect_to after_sign_in_path_for(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = SecureRandom.hex(50)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :can_login, :is_backup, :imap_password, :provider)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backup_helper.rb
module BackupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imap_providers_helper.rb
module ImapProvidersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br>
<h1>HOME

<div class="showbox">
  <div class="loader">
    <svg class="circular" viewBox="25 25 50 50">
      <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="4" stroke-miterlimit="10"/>
    </svg>
  </div>
</div>
</h1>
<br>




<%# Navbar%>
<div class="row">
<div class="col-2">
  <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">Home</a>
    <a class="nav-link" id="v-pills-add-new-user-tab" data-toggle="pill" href="#v-pills-add-new-user" role="tab" aria-controls="v-pills-add-new-user" aria-selected="false">Add A New User</a>
    <a class="nav-link" id="v-pills-add-imap-provider-tab" data-toggle="pill" href="#v-pills-add-imap-provider" role="tab" aria-controls="v-pills-add-imap-provider" aria-selected="false">Add A New Provider</a>
    <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Settings</a>
  </div>
</div>
<%# HOME - Display Users Table%>
<div class="col-10">
  <div class="tab-content" id="v-pills-tabContent">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <h2>Users</h3>
      <br>
      <table class="d-flex p2 table">
          <tr class="thead-dark">
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">E-Mail</th>
            <th scope="col">Can Login?</th>
            <th scope="col">Backup Mailbox?</th>
            <th scope="col">IMAP Provider</th>
            <th scope="col">Options</th>
          </tr>

          <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.can_login %></td>
            <td><%= user.is_backup %></td>
            <td><%= user.provider %></td>

            <td>
            <div class="dropdown">
              <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Actions
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="<%=user_path(user)%>">View More</a>
                <a class="dropdown-item" href="<%=edit_user_path(user)%>">Edit</a>
                <a class="dropdown-item-danger" href="" onclick='set_userID(<%=user.id%>, "<%=user.first_name%>", "<%=user.last_name%>");' data-toggle="modal" data-target="#delete-modal" >Delete</a>

              </div>
            </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <br>
      <br>
      <h2>Providers</h3>
      <br>
      <table class="d-flex p2 table">
        <tr class="thead-dark">
          <th>Name &nbsp; &nbsp; &nbsp;</th>
          <th>Server</th>
          <th>Port</th>
          <th>SSL</th>
        </tr>
        <% @imap_providers.each do |provider| %>
          <tr>
            <td><%= provider.name %></td>
            <td><%= provider.server %></td>
            <td><%= provider.port %></td>
            <td><%= provider.ssl %></td>
          </tr>
        <% end %>
      </table>
    </div>





<%# Add New User%>
  <div class="tab-pane fade" id="v-pills-add-new-user" role="tabpanel" aria-labelledby="v-pills-add-new-user-tab">
  <h3>Create a new user here...</h3>
    <%= form_for(User.new, :html => {:class => 'form_group'}) do |form| %>
      <div class='row'>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :first_name, class:'form-control', placeholder: 'first name' %>
          </div>
        </div>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :last_name, class:'form-control', placeholder: 'last name' %>
          </div>
        </div>
      </div>
      <div class='row'>
        <div class='col-2'>
          <div class='form-group'>
          <%= form.text_field :email, class:'form-control', placeholder: 'email' %>
          </div>
        </div>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :imap_password, class:'form-control', placeholder: 'imap password' %>
          </div>
        </div>
      </div>
      <br>
      <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <% i = 1%>
        <% ImapProvider.all.each do |provider| %>
        <br>
          <label class="btn btn-secondary active">
            <%= form.radio_button :provider, i%> <%= provider.name%>
          </label>
          <% i = i + 1%>
        <%end%>
      </div>
      <br>
      <br>
      <div class='form-check'>
        <%= form.check_box :can_login, class:'form-check-input', id:'can_login'%>
        <label for="can_login">Can this user login?</label>
      </div>
      <div class='form-check'>
        <%= form.check_box :is_backup, class:'form-check-input', id:'is_backup'%>
        <label for="is_backup">Backup This User?</label>
      </div>
      
      <br>
      <%= form.submit "Submit", class:'btn btn-primary' %>
    <% end %>
  </div>





<%# Add Imap Provider%>
  <div class="tab-pane fade" id="v-pills-add-imap-provider" role="tabpanel" aria-labelledby="v-pills-add-imap-provider-tab">
  <h3>Create a new provider here...</h3>
    <%= form_for(ImapProvider.new, :html => {:class => 'form_group'}) do |form| %>
      <div class='row'>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :name, class:'form-control', placeholder: 'i.e. Google' %>
          </div>
        </div>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :server, class:'form-control', placeholder: 'i.e. imap.gmail.com' %>
          </div>
        </div>
      </div>
      <div class='row'>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :port, class:'form-control', placeholder: 'i.e. 993' %>
          </div>
        </div>
      </div>
      <div class='form-check'>
        <%= form.check_box :ssl, class:'form-check-input', id:'ssl'%>
        <label for="can_login">Use SSL?</label>
      </div>
      <br>
      <%= form.submit "Submit", class:'btn btn-primary' %>
    <% end %>
  </div>
<%# Spare Page%>
  <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
    <p>You are running module imap-backup version <%= @imap_backup_version %></p>
    <%= link_to 'Start Manual Backup!', start_backup_path, method: :post %>





  </div>

  
</div>
















<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle">WAIT!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete <span style="font-weight:bold;" id="first-name"></span> <span style="font-weight:bold;" id="last-name"></span>?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success" data-dismiss="modal">No!</button>
        <a class="btn btn-danger" id="confirm-delete-btn" href="#" data-method="delete">Yes, Delete</a>
      </div>
    </div>
  </div>
</div>








<script>
  var userToDelete
  var userToDeleteFirstName
  var userToDeleteLastName
  function set_userID(userID, userFirstName, userLastName) {
    console.log(userID);
    userToDeleteFirstName = userFirstName;
    userToDeleteLastName = userLastName;
    document.getElementById("first-name").innerHTML=userFirstName;
    document.getElementById("last-name").innerHTML=userLastName;

    var usersURL = "/users/";
    userToDelete = usersURL.concat(userID);
    document.getElementById('confirm-delete-btn').href = userToDelete;
  }
</script>

app/views/imap_providers/_form.html.erb
<%= form_with(model: imap_provider, local: true) do |form| %>
  <% if imap_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(imap_provider.errors.count, "error") %> prohibited this imap_provider from being saved:</h2>

      <ul>
      <% imap_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imap_providers/edit.html.erb
<h1>Editing Imap Provider</h1>

<%= render 'form', imap_provider: @imap_provider %>

<%= link_to 'Show', @imap_provider %> |
<%= link_to 'Back', imap_providers_path %>

app/views/imap_providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Imap Providers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @imap_providers.each do |imap_provider| %>
      <tr>
        <td><%= link_to 'Show', imap_provider %></td>
        <td><%= link_to 'Edit', edit_imap_provider_path(imap_provider) %></td>
        <td><%= link_to 'Destroy', imap_provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Imap Provider', new_imap_provider_path %>

app/views/imap_providers/new.html.erb
<h1>New Imap Provider</h1>

<%= render 'form', imap_provider: @imap_provider %>

<%= link_to 'Back', imap_providers_path %>

app/views/imap_providers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_imap_provider_path(@imap_provider) %> |
<%= link_to 'Back', imap_providers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailArchiver</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

    <%= form_for(@user, :html => {:class => 'form_group'}) do |form| %>
      <div class='row'>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :first_name, class:'form-control', placeholder: 'first name' %>
          </div>
        </div>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :last_name, class:'form-control', placeholder: 'last name' %>
          </div>
        </div>
      </div>
      <div class='row'>
        <div class='col-2'>
          <div class='form-group'>
          <%= form.text_field :email, class:'form-control', placeholder: 'email' %>
          </div>
        </div>
        <div class='col-2'>
          <div class='form-group'>
            <%= form.text_field :imap_password, class:'form-control', placeholder: 'imap password' %>
          </div>
        </div>
      </div>
      <div class='col-2'>
        <div class='form-group'>
          <%= form.text_field :provider, class:'form-control', placeholder: 'provider' %>
        </div>
      </div>

      <div class='form-check'>
        <%= form.check_box :can_login, class:'form-check-input', id:'can_login'%>
        <label for="can_login">Can this user login?</label>
      </div>
      <div class='form-check'>
        <%= form.check_box :is_backup, class:'form-check-input', id:'is_backup'%>
        <label for="is_backup">Backup This User?</label>
      </div>
      
      <br>
      <%= form.submit "Submit", class:'btn btn-primary' %>
    <% end %>


<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  <% @users.each do |user| %>
    </br>
    <div >
        <%= user.email %>
    </div>
  <% end %>

    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for(@user) do |form| %>
    <%= form.text_field :first_name %>
    <%= form.text_field :last_name %>
    <%= form.text_field :email %>
    <%= form.text_field :password %>
    <%= form.submit "Submit" %>
      <% end %>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>